name: github pages Hugo Deploy

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
    branches:
      - main  # Set a branch to deploy
  schedule:
    - cron: "0 2 * * 1-6"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo -t docport

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
          user_name: 'WuZhuoran'
          user_email: 'munoliver007@gmail.com'
          allow_empty_commit: true
